// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryEwalletSettleProfileRequest struct {
	V2Common
	BmcpNo       string `json:"bmcpNo,omitempty"`
	MercId       string `json:"mercId,omitempty"`
	SettleType   string `json:"settleType,omitempty"`
	SettleTime   string `json:"settleTime,omitempty"`
	SettleCircle string `json:"settleCircle,omitempty"`
	PayType      string `json:"payType,omitempty"`
	NotifyUrl    string `json:"notifyUrl,omitempty"`
	RetainedAmt  string `json:"retainedAmt,omitempty"`
}

func (r *V2LaepIndustryEwalletSettleProfileRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryEwalletSettleProfileRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_EWALLET_SETTLEPROFILE
}
