// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepEwalletAccountQueryAcctInfoRequest struct {
	V2Common
	BmcpNo      string `json:"bmcpNo,omitempty"`
	MercId      string `json:"mercId,omitempty"`
	BalanceFlag string `json:"balanceFlag,omitempty"`
	Remark      string `json:"remark,omitempty"`
}

func (r *V2LaepEwalletAccountQueryAcctInfoRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepEwalletAccountQueryAcctInfoRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_EWALLETACCOUNT_QUERYACCTINFO
}
