// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepCreateEleReceiptRequest struct {
	V2Common
	BmcpNo    string `json:"bmcpNo,omitempty"`
	MercId    string `json:"mercId,omitempty"`
	AcctSysSq string `json:"acctSysSq,omitempty"`
}

func (r *V2LaepCreateEleReceiptRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepCreateEleReceiptRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_CREATEELERECEIPT
}
