// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryEwalletEwalletfeeRequest struct {
	V2Common
	BmcpNo    string `json:"bmcpNo,omitempty"`
	MercId    string `json:"mercId,omitempty"`
	FeeType   string `json:"feeType,omitempty"`
	FeeAmt    string `json:"feeAmt,omitempty"`
	MinFeeAmt string `json:"minFeeAmt,omitempty"`
	MaxFeeAmt string `json:"maxFeeAmt,omitempty"`
}

func (r *V2LaepIndustryEwalletEwalletfeeRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryEwalletEwalletfeeRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_EWALLET_EWALLETFEE
}
