// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepEwalletAccountBillsQryRequest struct {
	V2Common
	OrgNo      string `json:"orgNo,omitempty"`
	BmcpNo     string `json:"bmcpNo,omitempty"`
	AcctNo     string `json:"acctNo,omitempty"`
	CustNo     string `json:"custNo,omitempty"`
	PayType    string `json:"payType,omitempty"`
	Amntcd     string `json:"amntcd,omitempty"`
	BillSq     string `json:"billSq,omitempty"`
	OutTransSq string `json:"outTransSq,omitempty"`
	Sid        string `json:"sid,omitempty"`
	LklOrderNo string `json:"lklOrderNo,omitempty"`
	StartDate  string `json:"startDate,omitempty"`
	EndDate    string `json:"endDate,omitempty"`
	Page       int    `json:"page,omitempty"`
	Size       int    `json:"size,omitempty"`
}

func (r *V2LaepEwalletAccountBillsQryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepEwalletAccountBillsQryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_EWALLETACCOUNT_BILLSQRY
}
