// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryBankcardBindRequest struct {
	V2Common
	BmcpNo           string `json:"bmcpNo,omitempty"`
	MercId           string `json:"mercId,omitempty"`
	BankNo           string `json:"bankNo,omitempty"`
	BankName         string `json:"bankName,omitempty"`
	ClearingBankCode string `json:"clearingBankCode,omitempty"`
	BankcardNo       string `json:"bankcardNo,omitempty"`
	Type             string `json:"type,omitempty"`
	DefaultFlag      string `json:"defaultFlag,omitempty"`
	AcctCity         string `json:"acctCity,omitempty"`
	AcctBank         string `json:"acctBank,omitempty"`
	Validate         string `json:"validate,omitempty"`
	Remark           string `json:"remark,omitempty"`
}

func (r *V2LaepIndustryBankcardBindRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryBankcardBindRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_BANKCARD_BIND
}
