// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryBankcardListRequest struct {
	V2Common
	BmcpNo string `json:"bmcpNo,omitempty"`
	MercId string `json:"mercId,omitempty"`
}

func (r *V2LaepIndustryBankcardListRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryBankcardListRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_BANKCARD_LIST
}
