// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryEwalletWithdrawRequest struct {
	V2Common
	OrgNo      string `json:"orgNo,omitempty"`
	MerchantNo string `json:"merchantNo,omitempty"`
	DrawAmt    string `json:"drawAmt,omitempty"`
	DrawMode   string `json:"drawMode,omitempty"`
	NotifyUrl  string `json:"notifyUrl,omitempty"`
	MerOrderNo string `json:"merOrderNo,omitempty"`
	PayNo      string `json:"payNo,omitempty"`
	PayType    string `json:"payType,omitempty"`
	Remark     string `json:"remark,omitempty"`
	BankId     string `json:"bankId,omitempty"`
}

func (r *V2LaepIndustryEwalletWithdrawRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryEwalletWithdrawRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_EWALLETWITHDRAW
}
