// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryTransferQueryRequest struct {
	V2Common
	OutBmcpNo  string `json:"outBmcpNo,omitempty"`
	OutMercId  string `json:"outMercId,omitempty"`
	MerOrderNo string `json:"merOrderNo,omitempty"`
	OrderNo    string `json:"orderNo,omitempty"`
}

func (r *V2LaepIndustryTransferQueryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryTransferQueryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_TRANSFER_QUERY
}
