// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryEwalletBalanceQueryRequest struct {
	V2Common
	OrgNo      string `json:"orgNo,omitempty"`
	MerchantNo string `json:"merchantNo,omitempty"`
	PayNo      string `json:"payNo,omitempty"`
	PayType    string `json:"payType,omitempty"`
}

func (r *V2LaepIndustryEwalletBalanceQueryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryEwalletBalanceQueryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_EWALLETBALANCEQUERY
}
