// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryBankcardUnbindRequest struct {
	V2Common
	BmcpNo string `json:"bmcpNo,omitempty"`
	MercId string `json:"mercId,omitempty"`
	BankId string `json:"bankId,omitempty"`
	Remark string `json:"remark,omitempty"`
}

func (r *V2LaepIndustryBankcardUnbindRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryBankcardUnbindRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_BANKCARD_UNBIND
}
