// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryEwalletWithdrawD1Request struct {
	V2Common
	OrgNo      string `json:"orgNo,omitempty"`
	MerchantNo string `json:"merchantNo,omitempty"`
	DrawAmt    string `json:"drawAmt,omitempty"`
	NotifyUrl  string `json:"notifyUrl,omitempty"`
	MerOrderNo string `json:"merOrderNo,omitempty"`
	PayNo      string `json:"payNo,omitempty"`
	PayType    string `json:"payType,omitempty"`
	Remark     string `json:"remark,omitempty"`
	Summary    string `json:"summary,omitempty"`
	BankId     string `json:"bankId,omitempty"`
}

func (r *V2LaepIndustryEwalletWithdrawD1Request) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryEwalletWithdrawD1Request) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_EWALLETWITHDRAWD1
}
