// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryEwalletWithdrawQueryRequest struct {
	V2Common
	OrgNo      string `json:"orgNo,omitempty"`
	MerchantNo string `json:"merchantNo,omitempty"`
	DrawJnl    string `json:"drawJnl,omitempty"`
	MerOrderNo string `json:"merOrderNo,omitempty"`
}

func (r *V2LaepIndustryEwalletWithdrawQueryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryEwalletWithdrawQueryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_EWALLETWITHDRAWQUERY
}
