// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2LaepIndustryTransferDirectRequest struct {
	V2Common
	OutBmcpNo   string `json:"outBmcpNo,omitempty"`
	OutMercId   string `json:"outMercId,omitempty"`
	OutAcctType string `json:"outAcctType,omitempty"`
	InBmcpNo    string `json:"inBmcpNo,omitempty"`
	InMercId    string `json:"inMercId,omitempty"`
	InPayType   string `json:"inPayType,omitempty"`
	MerOrderNo  string `json:"merOrderNo,omitempty"`
	Amount      string `json:"amount,omitempty"`
	Remark      string `json:"remark,omitempty"`
}

func (r *V2LaepIndustryTransferDirectRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2LaepIndustryTransferDirectRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_LAEP_INDUSTRY_TRANSFER_DIRECT
}
