// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

// 原sdk无此接口和代码，新增
type V2MmsOpenApiLedgerDetailLedgerReceiverRequest struct {
	V2Common
	Version string `json:"version"`
	OrderNo string `json:"orderNo"`
	OrgCode string `json:"orgCode"`
	//MerCupNo   string `json:"merCupNo"`
	//MerInnerNo string `json:"merInnerNo"`
	ReceiverNo string `json:"receiverNo"`
}

func (r *V2MmsOpenApiLedgerDetailLedgerReceiverRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2MmsOpenApiLedgerDetailLedgerReceiverRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_MMS_OPENAPI_LEDGER_DETAILlLEDGERRECEIVER
}
