// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2MrssQueryQueryAcctInfoRequest struct {
	V2Common
	QryNo       string `json:"qryNo,omitempty"`
	MerId       string `json:"merId,omitempty"`
	BalanceFlag string `json:"balanceFlag,omitempty"`
}

func (r *V2MrssQueryQueryAcctInfoRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2MrssQueryQueryAcctInfoRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_MRSSQUERY_QUERYACCTINFO
}
