// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2MmsOpenApiUploadFileRequest struct {
	V2Common
	Version    string `json:"version,omitempty"`
	OrderNo    string `json:"orderNo,omitempty"`
	OrgCode    string `json:"orgCode,omitempty"`
	AttType    string `json:"attType,omitempty"`
	AttExtName string `json:"attExtName,omitempty"`
	AttContext string `json:"attContext,omitempty"`
}

func (r *V2MmsOpenApiUploadFileRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2MmsOpenApiUploadFileRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_MMS_OPENAPI_UPLOADFILE
}
