// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2MmsOpenApiLedgerModifyLedgerReceiverRequest struct {
	V2Common
	Version           string                                                    `json:"version,omitempty"`
	OrderNo           string                                                    `json:"orderNo,omitempty"`
	OrgCode           string                                                    `json:"orgCode,omitempty"`
	ReceiverNo        string                                                    `json:"receiverNo,omitempty"`
	ReceiverName      string                                                    `json:"receiverName,omitempty"`
	ContactMobile     string                                                    `json:"contactMobile,omitempty"`
	AcctNo            string                                                    `json:"acctNo,omitempty"`
	AcctTypeCode      string                                                    `json:"acctTypeCode,omitempty"`
	AcctOpenBankCode  string                                                    `json:"acctOpenBankCode,omitempty"`
	AcctOpenBankName  string                                                    `json:"acctOpenBankName,omitempty"`
	AcctClearBankCode string                                                    `json:"acctClearBankCode,omitempty"`
	AttachList        []V2MmsOpenApiLedgerModifyLedgerReceiverRequestAttachInfo `json:"attachList,omitempty"`
}

func (r *V2MmsOpenApiLedgerModifyLedgerReceiverRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2MmsOpenApiLedgerModifyLedgerReceiverRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_MMS_OPENAPI_LEDGER_MODIFYLEDGERRECEIVER
}

type V2MmsOpenApiLedgerModifyLedgerReceiverRequestAttachInfo struct {
	AttachType      string `json:"attachType,omitempty"`
	AttachName      string `json:"attachName,omitempty"`
	AttachStorePath string `json:"attachStorePath,omitempty"`
}
