// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2MmsOpenApiLedgerModifyLedgerMerRequest struct {
	V2Common
	Version              string `json:"version,omitempty"`
	OrderNo              string `json:"orderNo,omitempty"`
	OrgCode              string `json:"orgCode,omitempty"`
	MerInnerNo           string `json:"merInnerNo,omitempty"`
	MerCupNo             string `json:"merCupNo,omitempty"`
	ContactMobile        string `json:"contactMobile,omitempty"`
	SplitLowestRatio     string `json:"splitLowestRatio,omitempty"`
	SplitEntrustFileName string `json:"splitEntrustFileName,omitempty"`
	SplitEntrustFilePath string `json:"splitEntrustFilePath,omitempty"`
	SplitRange           string `json:"splitRange,omitempty"` //ALL：全部交易分账 (商户所有交易默认待分账)MARK：标记交易分账(只有带分账标识交易待分账，其余交易正常结算)默认：MARK
	RetUrl               string `json:"retUrl,omitempty"`
}

func (r *V2MmsOpenApiLedgerModifyLedgerMerRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2MmsOpenApiLedgerModifyLedgerMerRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_MMS_OPENAPI_LEDGER_MODIFYLEDGERMER
}
