// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2MmsOpenApiLedgerApplyUnBindRequest struct {
	V2Common
	Version         string `json:"version,omitempty"`
	OrderNo         string `json:"orderNo,omitempty"`
	OrgCode         string `json:"orgCode,omitempty"`
	MerInnerNo      string `json:"merInnerNo,omitempty"`
	MerCupNo        string `json:"merCupNo,omitempty"`
	ReceiverNo      string `json:"receiverNo,omitempty"`
	EntrustFileName string `json:"entrustFileName,omitempty"`
	EntrustFilePath string `json:"entrustFilePath,omitempty"`
	Remark          string `json:"remark,omitempty"`
	RetUrl          string `json:"retUrl,omitempty"`
}

func (r *V2MmsOpenApiLedgerApplyUnBindRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2MmsOpenApiLedgerApplyUnBindRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_MMS_OPENAPI_LEDGER_APPLYUNBIND
}
