// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2MmsOpenApiLedgerApplyLedgerReceiverRequest struct {
	V2Common
	Version                    string                                                   `json:"version,omitempty"`
	OrderNo                    string                                                   `json:"orderNo,omitempty"`
	OrgCode                    string                                                   `json:"orgCode,omitempty"`
	ReceiverName               string                                                   `json:"receiverName,omitempty"`
	ContactMobile              string                                                   `json:"contactMobile,omitempty"`
	LicenseNo                  string                                                   `json:"licenseNo,omitempty"`
	LicenseName                string                                                   `json:"licenseName,omitempty"`
	LegalPersonName            string                                                   `json:"legalPersonName,omitempty"`
	LegalPersonCertificateType string                                                   `json:"legalPersonCertificateType,omitempty"`
	LegalPersonCertificateNo   string                                                   `json:"legalPersonCertificateNo,omitempty"`
	AcctNo                     string                                                   `json:"acctNo,omitempty"`
	AcctName                   string                                                   `json:"acctName,omitempty"`
	AcctTypeCode               string                                                   `json:"acctTypeCode,omitempty"`
	AcctCertificateType        string                                                   `json:"acctCertificateType,omitempty"`
	AcctCertificateNo          string                                                   `json:"acctCertificateNo,omitempty"`
	AcctOpenBankCode           string                                                   `json:"acctOpenBankCode,omitempty"`
	AcctOpenBankName           string                                                   `json:"acctOpenBankName,omitempty"`
	AcctClearBankCode          string                                                   `json:"acctClearBankCode,omitempty"`
	AttachList                 []V2MmsOpenApiLedgerApplyLedgerReceiverRequestAttachInfo `json:"attachList,omitempty"`
}

func (r *V2MmsOpenApiLedgerApplyLedgerReceiverRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2MmsOpenApiLedgerApplyLedgerReceiverRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_MMS_OPENAPI_LEDGER_APPLYLEDGERRECEIVER
}

type V2MmsOpenApiLedgerApplyLedgerReceiverRequestAttachInfo struct {
	AttachType      string `json:"attachType,omitempty"`
	AttachName      string `json:"attachName,omitempty"`
	AttachStorePath string `json:"attachStorePath,omitempty"`
}
