// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V2McqsLimitQueryLimitRequest struct {
	V2Common
	MerCupNo string `json:"merCupNo,omitempty"`
	OrderNo  string `json:"orderNo,omitempty"`
}

func (r *V2McqsLimitQueryLimitRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V2McqsLimitQueryLimitRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V2_MCQS_LIMIT_QUERYLIMIT
}
