// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3CcssCounterOrderQueryRequest struct {
	V3Common
	OutOrderNo string `json:"out_order_no,omitempty"`
	MerchantNo string `json:"merchant_no,omitempty"`
	PayOrderNo string `json:"pay_order_no,omitempty"`
	ChannelId  string `json:"channel_id,omitempty"`
}

func (r *V3CcssCounterOrderQueryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3CcssCounterOrderQueryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_CCSS_COUNTER_ORDER_QUERY
}
