// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3CcssCounterOrderSpecialCreateRequest struct {
	V3Common
	OutOrderNo           string                                              `json:"out_order_no,omitempty"`
	MerchantNo           string                                              `json:"merchant_no,omitempty"`
	VposId               string                                              `json:"vpos_id,omitempty"`
	ChannelId            string                                              `json:"channel_id,omitempty"`
	BusiMode             string                                              `json:"busi_mode,omitempty"`
	TotalAmount          int64                                               `json:"total_amount,omitempty"`
	OrderEfficientTime   string                                              `json:"order_efficient_time,omitempty"`
	NotifyUrl            string                                              `json:"notify_url,omitempty"`
	SupportCancel        int                                                 `json:"support_cancel,omitempty"`
	SupportRefund        int                                                 `json:"support_refund,omitempty"`
	SupportRepeatPay     int                                                 `json:"support_repeat_pay,omitempty"`
	OutUserId            string                                              `json:"out_user_id,omitempty"`
	CallbackUrl          string                                              `json:"callback_url,omitempty"`
	OrderInfo            string                                              `json:"order_info,omitempty"`
	TermNo               string                                              `json:"term_no,omitempty"`
	SplitMark            string                                              `json:"split_mark,omitempty"`
	SettleType           string                                              `json:"settle_type,omitempty"`
	OutSplitInfo         []model.V3CcssOrderOutSplitInfo                     `json:"out_split_info,omitempty"`
	CounterParam         string                                              `json:"counter_param,omitempty"`
	CounterRemark        string                                              `json:"counter_remark,omitempty"`
	BusiTypeParam        string                                              `json:"busi_type_param,omitempty"`
	SgnInfo              []string                                            `json:"sgn_info,omitempty"`
	TransferField        V3CcssCounterOrderSpecialCreateRequestTransferField `json:"transfer_field,omitempty"`
	IdentityInfo         string                                              `json:"identity_info,omitempty"`
	ProductId            string                                              `json:"product_id,omitempty"`
	GoodsMark            string                                              `json:"goods_mark,omitempty"`
	GoodsField           string                                              `json:"goods_field,omitempty"`
	OrderSceneField      model.V3CcssOrderSceneFieldInfo                     `json:"order_scene_field,omitempty"`
	AgeLimit             string                                              `json:"age_limit,omitempty"`
	RepeatPayAutoRefund  string                                              `json:"repeat_pay_auto_refund,omitempty"`
	RepeatPayNotify      string                                              `json:"repeat_pay_notify,omitempty"`
	CloseOrderAutoRefund string                                              `json:"close_order_auto_refund,omitempty"`
	TransCurrency        string                                              `json:"trans_currency,omitempty"`
	ShopName             string                                              `json:"shop_name,omitempty"`
}

func (r *V3CcssCounterOrderSpecialCreateRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3CcssCounterOrderSpecialCreateRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_CCSS_COUNTER_ORDER_SPECIAL_CREATE
}

type V3CcssCounterOrderSpecialCreateRequestTransferField struct {
	AccOutNo   string `json:"acc_out_no,omitempty"`
	AccOutName string `json:"acc_out_name,omitempty"`
	Additional string `json:"additional,omitempty"`
}
