// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3CcssCounterOrderSpecialCreateEncryRequest struct {
	V3CcssCounterOrderSpecialCreateRequest
}

func (r *V3CcssCounterOrderSpecialCreateEncryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_CCSS_COUNTER_ORDER_SPECIAL_CREATE_ENCRY
}
