// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3IpsqpQueryQuerySignByPanRequest struct {
	V3Common
	MerchantNo string `json:"merchant_no,omitempty"`
	AccNo      string `json:"acc_no,omitempty"`
	TradeCode  string `json:"trade_code,omitempty"`
}

func (r *V3IpsqpQueryQuerySignByPanRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsqpQueryQuerySignByPanRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSQP_QUERY_QUERYSIGNBYPAN
}
