// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3IpsqpTransQuickSignConfirmRequest struct {
	V3Common
	MerchantNo   string                  `json:"merchant_no,omitempty"`
	TermNo       string                  `json:"term_no,omitempty"`
	OutTradeNo   string                  `json:"out_trade_no,omitempty"`
	TradeNo      string                  `json:"trade_no,omitempty"`
	AccNo        string                  `json:"acc_no,omitempty"`
	CardType     string                  `json:"card_type,omitempty"`
	IssInsCode   string                  `json:"iss_ins_code,omitempty"`
	IssInsName   string                  `json:"iss_ins_name,omitempty"`
	CustomerInfo model.V3IpsCustomerInfo `json:"customer_info,omitempty"`
}

func (r *V3IpsqpTransQuickSignConfirmRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsqpTransQuickSignConfirmRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSQP_TRANS_QUICKSIGNCONFIRM
}
