// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3IpsdkTransRealTimeCollectionRequest struct {
	V3Common
	MerchantNo   string `json:"merchant_no,omitempty"`
	TermNo       string `json:"term_no,omitempty"`
	OutTradeNo   string `json:"out_trade_no,omitempty"`
	TxnTime      string `json:"txn_time,omitempty"`
	CurrencyCode string `json:"currency_code,omitempty"`
	TxnAmt       string `json:"txn_amt,omitempty"`
	SgnNo        string `json:"sgn_no,omitempty"`
	BillType     string `json:"bill_type,omitempty"`
	BillNo       string `json:"bill_no,omitempty"`
	BizType      string `json:"biz_type,omitempty"`
	NotifyUrl    string `json:"notify_url,omitempty"`
	PayOrderNo   string `json:"pay_order_no,omitempty"`
	SettleType   string `json:"settle_type,omitempty"`
}

func (r *V3IpsdkTransRealTimeCollectionRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsdkTransRealTimeCollectionRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSDK_TRANS_REALTIMECOLLECTION
}
