// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3IpsdkTransBatchQueryRequest struct {
	V3Common
	MerchantNo string `json:"merchant_no,omitempty"`
	TermNo     string `json:"term_no,omitempty"`
	BatchNo    string `json:"batch_no,omitempty"`
	TxnTime    string `json:"txn_time,omitempty"`
}

func (r *V3IpsdkTransBatchQueryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsdkTransBatchQueryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSDK_TRANS_BATCHQUERY
}
