// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3IpsqpTransGatewaySignRequest struct {
	V3Common
	MerchantNo    string `json:"merchant_no,omitempty"`
	OutTradeNo    string `json:"out_trade_no,omitempty"`
	Pan           string `json:"pan,omitempty"`
	AcctName      string `json:"acct_name,omitempty"`
	BankCode      string `json:"bank_code,omitempty"`
	CardType      string `json:"card_type,omitempty"`
	BkMobile      string `json:"bk_mobile,omitempty"`
	CertType      string `json:"cert_type,omitempty"`
	CertNo        string `json:"cert_no,omitempty"`
	Cvn2          string `json:"cvn2,omitempty"`
	VaDate        string `json:"va_date,omitempty"`
	AgreementInfo string `json:"agreement_info,omitempty"`
	LcUrl         string `json:"lc_url,omitempty"`
	NotifyUrl     string `json:"notify_url,omitempty"`
	PyerTrxTrmTp  string `json:"pyer_trx_trm_tp,omitempty"`
	GwChnnlTp     string `json:"gw_chnnl_tp,omitempty"`
}

func (r *V3IpsqpTransGatewaySignRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsqpTransGatewaySignRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSQP_TRANS_GATEWAYSIGN
}
