// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3IpsdfPaidQueryRequest struct {
	V3Common
	MerchantNo string `json:"merchant_no,omitempty"`
	TermNo     string `json:"term_no,omitempty"`
	OutTradeNo string `json:"out_trade_no,omitempty"`
	TradeNo    string `json:"trade_no,omitempty"`
}

func (r *V3IpsdfPaidQueryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsdfPaidQueryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSDF_PAID_QUERY
}
