// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3IpsqpTransApplySignAndPayRequest struct {
	V3Common
	MerchantNo  string                  `json:"merchant_no,omitempty"`
	TermNo      string                  `json:"term_no,omitempty"`
	OutTradeNo  string                  `json:"out_trade_no,omitempty"`
	TotalAmount string                  `json:"total_amount,omitempty"`
	Subject     string                  `json:"subject,omitempty"`
	Detail      string                  `json:"detail,omitempty"`
	SgnInf      model.V3IpsSgnInfo      `json:"sgn_inf,omitempty"`
	DiscountInf model.V3IpsDiscountInfo `json:"discount_inf,omitempty"`
	RskInf      model.V3IpsRskInfo      `json:"rsk_inf,omitempty"`
	TermInfo    model.V3IpsTermInfo     `json:"term_info,omitempty"`
}

func (r *V3IpsqpTransApplySignAndPayRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsqpTransApplySignAndPayRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSQP_TRANS_APPLYSIGNANDPAY
}
