// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3IpsdkTransCollectionSignCancelRequest struct {
	V3Common
	MerchantNo string `json:"merchant_no,omitempty"`
	TermNo     string `json:"term_no,omitempty"`
	OutTradeNo string `json:"out_trade_no,omitempty"`
	TxnTime    string `json:"txn_time,omitempty"`
	SgnNo      string `json:"sgn_no,omitempty"`
}

func (r *V3IpsdkTransCollectionSignCancelRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsdkTransCollectionSignCancelRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSDK_TRANS_COLLECTIONSIGNCANCEL
}
