// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3IpsqpTransConfirmSignAndPayRequest struct {
	V3Common
	MerchantNo      string `json:"merchant_no,omitempty"`
	TermNo          string `json:"term_no,omitempty"`
	TradeNo         string `json:"trade_no,omitempty"`
	OutTradeNo      string `json:"out_trade_no,omitempty"`
	TotalAmount     string `json:"total_amount,omitempty"`
	IdentifyingCode string `json:"identifying_code,omitempty"`
}

func (r *V3IpsqpTransConfirmSignAndPayRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsqpTransConfirmSignAndPayRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSQP_TRANS_CONFIRMSIGNANDPAY
}
