// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3IpsdkTransCollectionSignApplyRequest struct {
	V3Common
	MerchantNo string `json:"merchant_no,omitempty"`
	TermNo     string `json:"term_no,omitempty"`
	OutTradeNo string `json:"out_trade_no,omitempty"`
	TxnTime    string `json:"txn_time,omitempty"`
	AccNo      string `json:"acc_no,omitempty"`
	AccType    string `json:"acc_type,omitempty"`
	IssInsCode string `json:"iss_ins_code,omitempty"`
	IssInsName string `json:"iss_ins_name,omitempty"`
	BillType   string `json:"bill_type,omitempty"`
	BillNo     string `json:"bill_no,omitempty"`
	BizType    string `json:"biz_type,omitempty"`
	ValidMonth string `json:"valid_month,omitempty"`
	Frequency  string `json:"frequency,omitempty"`
	MaxLimit   string `json:"max_limit,omitempty"`
	MinLimit   string `json:"min_limit,omitempty"`
	PhoneNo    string `json:"phone_no,omitempty"`
}

func (r *V3IpsdkTransCollectionSignApplyRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsdkTransCollectionSignApplyRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSDK_TRANS_COLLECTIONSIGNAPPLY
}
