// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3IpsdfPaidBatchPayRequest struct {
	V3Common
	MerchantNo string `json:"merchant_no,omitempty"`
	TermNo     string `json:"term_no,omitempty"`
	PeriodType string `json:"period_type,omitempty"`
	BatchNo    string `json:"batch_no,omitempty"`
	TotalQty   string `json:"total_qty,omitempty"`
	TotalAmt   string `json:"total_amt,omitempty"`
	FileName   string `json:"file_name,omitempty"`
	Digest     string `json:"digest,omitempty"`
}

func (r *V3IpsdfPaidBatchPayRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsdfPaidBatchPayRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSDF_PAID_BATCHPAY
}
