// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3IpsdfPaidPayRequest struct {
	V3Common
	MerchantNo string                 `json:"merchant_no,omitempty"`
	TermNo     string                 `json:"term_no,omitempty"`
	OutTradeNo string                 `json:"out_trade_no,omitempty"`
	TxnAmt     string                 `json:"txn_amt,omitempty"`
	PeriodType string                 `json:"period_type,omitempty"`
	Remark     string                 `json:"remark,omitempty"`
	Summary    string                 `json:"summary,omitempty"`
	PayerInfo  model.V3IpsdfPayerInfo `json:"payer_info,omitempty"`
	SubVirAcct string                 `json:"sub_vir_acct,omitempty"`
}

func (r *V3IpsdfPaidPayRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsdfPaidPayRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSDF_PAID_PAY
}
