// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3IpsdkTransCollectionSignConfirmRequest struct {
	V3Common
	MerchantNo   string                  `json:"merchant_no,omitempty"`
	TermNo       string                  `json:"term_no,omitempty"`
	OutTradeNo   string                  `json:"out_trade_no,omitempty"`
	TxnTime      string                  `json:"txn_time,omitempty"`
	CustomerInfo model.V3IpsCustomerInfo `json:"customer_info,omitempty"`
}

func (r *V3IpsdkTransCollectionSignConfirmRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3IpsdkTransCollectionSignConfirmRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_IPSDK_TRANS_COLLECTIONSIGNCONFIRM
}
