// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3LabsTransPreorderEncryRequest struct {
	V3LabsTransPreorderRequest
}

func (r *V3LabsTransPreorderEncryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LABS_TRANS_PREORDER_ENCRY
}
