// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3LabsTransPreorderRequest struct {
	V3Common
	MerchantNo  string `json:"merchant_no,omitempty"`
	TermNo      string `json:"term_no,omitempty"`
	OutTradeNo  string `json:"out_trade_no,omitempty"` //商户系统唯一，对应数据库表中外部请求流水号。
	AccountType string `json:"account_type,omitempty"` //微信：WECHAT 支付宝：ALIPAY 银联：UQRCODEPAY 翼支付: BESTPAY 苏宁易付宝: SUNING 拉卡拉支付账户：LKLACC 网联小钱包：NUCSPAY 京东钱包：JD

	//41:NATIVE（（ALIPAY，云闪付支持，京东白条分期）	51:JSAPI（微信公众号支付，支付宝服务窗支付，银联JS支付，翼支付JS支付, 拉卡拉钱包支付, 京东白条分期）71:微信小程序支付61:APP支付（微信APP支付）
	TransType string `json:"trans_type,omitempty"`

	TotalAmount int `json:"total_amount,omitempty"`

	LocationInfo model.V3LabsTradeLocationInfo `json:"location_info,omitempty"`

	BusiMode   string `json:"busi_mode,omitempty"`
	Subject    string `json:"subject,omitempty"`
	PayOrderNo string `json:"pay_order_no,omitempty"`

	NotifyUrl     string `json:"notify_url,omitempty"` // 商户通知地址
	SettleType    string `json:"settle_type,omitempty"`
	Remark        string `json:"remark,omitempty"`
	IdentityInfo  string `json:"identity_info,omitempty"`
	PromoInfo     string `json:"promo_info,omitempty"`
	AccBusiFields any    `json:"acc_busi_fields,omitempty"`
}

func (r *V3LabsTransPreorderRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3LabsTransPreorderRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LABS_TRANS_PREORDER
}
