// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3LamsTradeTradeRefundQueryRequest struct {
	V3Common
	MerchantNo       string `json:"merchant_no,omitempty"`
	TermNo           string `json:"term_no,omitempty"`
	OutTradeNo       string `json:"out_trade_no,omitempty"`
	OriginTradeDate  string `json:"origin_trade_date,omitempty"`
	OriginBizType    string `json:"origin_biz_type,omitempty"`
	OriginTradeNo    string `json:"origin_trade_no,omitempty"`
	OriginTradeRefNo string `json:"origin_trade_ref_no,omitempty"`
	OriginOutTradeNo string `json:"origin_out_trade_no,omitempty"`
}

func (r *V3LamsTradeTradeRefundQueryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3LamsTradeTradeRefundQueryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LAMS_TRADE_TRADE_REFUND_QUERY
}
