// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3LabsTransMicropayEncryRequest struct {
	V3LabsTransMicropayRequest
}

func (r *V3LabsTransMicropayEncryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LABS_TRANS_MICROPAY_ENCRY
}
