// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3LabsTransMicropayRequest struct {
	V3Common
	MerchantNo    string                        `json:"merchant_no,omitempty"`
	TermNo        string                        `json:"term_no,omitempty"`
	OutTradeNo    string                        `json:"out_trade_no,omitempty"`
	AuthCode      string                        `json:"auth_code,omitempty"`
	TotalAmount   string                        `json:"total_amount,omitempty"`
	LocationInfo  model.V3LabsTradeLocationInfo `json:"location_info,omitempty"`
	BusiMode      string                        `json:"busi_mode,omitempty"`
	Subject       string                        `json:"subject,omitempty"`
	PayOrderNo    string                        `json:"pay_order_no,omitempty"`
	NotifyUrl     string                        `json:"notify_url,omitempty"`
	SettleType    string                        `json:"settle_type,omitempty"`
	Remark        string                        `json:"remark,omitempty"`
	ScanType      string                        `json:"scan_type,omitempty"`
	IdentityInfo  string                        `json:"identity_info,omitempty"`
	PromoInfo     string                        `json:"promo_info,omitempty"`
	AccBusiFields any                           `json:"acc_busi_fields,omitempty"`
}

func (r *V3LabsTransMicropayRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3LabsTransMicropayRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LABS_TRANS_MICROPAY
}
