// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3LabsRelationRevokedRequest struct {
	V3Common
	MerchantNo       string                        `json:"merchant_no,omitempty"`
	TermNo           string                        `json:"term_no,omitempty"`
	OutTradeNo       string                        `json:"out_trade_no,omitempty"`
	OriginOutTradeNo string                        `json:"origin_out_trade_no,omitempty"`
	OriginTradeNo    string                        `json:"origin_trade_no,omitempty"`
	LocationInfo     model.V3LabsTradeLocationInfo `json:"location_info,omitempty"`
}

func (r *V3LabsRelationRevokedRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3LabsRelationRevokedRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LABS_RELATION_REVOKED
}
