// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3LamsTradeTradeRefundRequest struct {
	V3Common
	MerchantNo      string                        `json:"merchant_no,omitempty"`
	TermNo          string                        `json:"term_no,omitempty"`
	OutTradeNo      string                        `json:"out_trade_no,omitempty"`
	RefundAmount    string                        `json:"refund_amount,omitempty"`
	OriginBizType   string                        `json:"origin_biz_type,omitempty"`
	OriginTradeDate string                        `json:"origin_trade_date,omitempty"`
	OriginLogNo     string                        `json:"origin_log_no,omitempty"`
	OriginTradeNo   string                        `json:"origin_trade_no,omitempty"`
	OriginCardNo    string                        `json:"origin_card_no,omitempty"`
	RefundType      string                        `json:"refund_type,omitempty"`
	LocationInfo    model.V3LabsTradeLocationInfo `json:"location_info,omitempty"`
}

func (r *V3LamsTradeTradeRefundRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3LamsTradeTradeRefundRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LAMS_TRADE_TRADE_REFUND
}
