// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3LabsTransShareCodeRequest struct {
	V3Common
	MerchantNo      string                                  `json:"merchant_no,omitempty"`
	TermNo          string                                  `json:"term_no,omitempty"`
	OutTradeNo      string                                  `json:"out_trade_no,omitempty"`
	AccountType     string                                  `json:"account_type,omitempty"`
	TotalAmount     string                                  `json:"total_amount,omitempty"`
	LocationInfo    model.V3LabsTradeLocationInfo           `json:"location_info,omitempty"`
	CodeValidPeriod string                                  `json:"code_valid_period,omitempty"`
	AccBusiFields   model.V3LabsTransShareCodeBusiFieldInfo `json:"acc_busi_fields,omitempty"`
}

func (r *V3LabsTransShareCodeRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3LabsTransShareCodeRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LABS_TRANS_SHARE_CODE
}
