// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3LabsQueryIdmrefundqueryRequest struct {
	V3Common
	MerchantNo       string `json:"merchant_no,omitempty"`
	TermNo           string `json:"term_no,omitempty"`
	OutRefundOrderNo string `json:"out_refund_order_no,omitempty"`
}

func (r *V3LabsQueryIdmrefundqueryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3LabsQueryIdmrefundqueryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LABS_QUERY_IDMREFUNDQUERY
}
