// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3LamsMerchantQueryTransRequest struct {
	V3Common
	MerchantNo string `json:"merchant_no,omitempty"`
	TermNo     string `json:"term_no,omitempty"`
	LogNo      string `json:"log_no,omitempty"`
}

func (r *V3LamsMerchantQueryTransRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3LamsMerchantQueryTransRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LAMS_MERCHANT_QUERY_TRANS
}
