// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3LabsQueryGetfaceauthinfoRequest struct {
	V3Common
	MerchantNo string `json:"merchant_no,omitempty"`
	TermNo     string `json:"term_no,omitempty"`
	StoreName  string `json:"store_name,omitempty"`
	StoreId    string `json:"store_id,omitempty"`
	Rawdata    string `json:"rawdata,omitempty"`
	SubAppId   string `json:"sub_app_id,omitempty"`
	Attach     string `json:"attach,omitempty"`
}

func (r *V3LabsQueryGetfaceauthinfoRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3LabsQueryGetfaceauthinfoRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_LABS_QUERY_GETFACEAUTHINFO
}
