// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/request/model"
)

type V3RfdRefundFrontMergeRefundRequest struct {
	V3Common
	MerchantNo         string                        `json:"merchant_no,omitempty"`
	TermNo             string                        `json:"term_no,omitempty"`
	OutTradeNo         string                        `json:"out_trade_no,omitempty"`
	RefundAmount       string                        `json:"refund_amount,omitempty"`
	RefundReason       string                        `json:"refund_reason,omitempty"`
	OriginLogNo        string                        `json:"origin_log_no,omitempty"`
	OriginOutTradeNo   string                        `json:"origin_out_trade_no,omitempty"`
	OriginTradeNo      string                        `json:"origin_trade_no,omitempty"`
	RefundAccMode      string                        `json:"refund_acc_mode,omitempty"`
	OutRefundSplitInfo []model.V3RefundSplitInfo     `json:"out_refund_split_info,omitempty"`
	LocationInfo       model.V3LabsTradeLocationInfo `json:"location_info,omitempty"`
}

func (r *V3RfdRefundFrontMergeRefundRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3RfdRefundFrontMergeRefundRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_RFD_REFUND_FRONT_MERGE_REFUND
}
