// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3RfdRefundFrontRefundFeeRequest struct {
	V3Common
	MerchantNo       string `json:"merchant_no,omitempty"`
	TermNo           string `json:"term_no,omitempty"`
	OutTradeNo       string `json:"out_trade_no,omitempty"`
	RefundAmount     string `json:"refund_amount,omitempty"`
	OriginLogNo      string `json:"origin_log_no,omitempty"`
	OriginOutTradeNo string `json:"origin_out_trade_no,omitempty"`
	OriginTradeNo    string `json:"origin_trade_no,omitempty"`
}

func (r *V3RfdRefundFrontRefundFeeRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3RfdRefundFrontRefundFeeRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_RFD_REFUND_FRONT_REFUND_FEE
}
