// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3SacsBalanceSeparateQueryRequest struct {
	V3Common
	MerchantNo    string `json:"merchant_no,omitempty"`
	SeparateNo    string `json:"separate_no,omitempty"`
	OutSeparateNo string `json:"out_separate_no,omitempty"`
}

func (r *V3SacsBalanceSeparateQueryRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3SacsBalanceSeparateQueryRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_SACS_BALANCESEPARATEQUERY
}
