// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3SacsSeparateRequest struct {
	V3Common
	MerchantNo    string                          `json:"merchant_no,omitempty"`
	LogNo         string                          `json:"log_no,omitempty"`   //  主扫交易中 成功状态 回调里面的logNo，或者查询成功状态的logNo
	LogDate       string                          `json:"log_date,omitempty"` // 记录日志 时间yyyyMMdd
	OutSeparateNo string                          `json:"out_separate_no,omitempty"`
	TotalAmt      string                          `json:"total_amt,omitempty"` // 分账金额
	LklOrgNo      string                          `json:"lkl_org_no,omitempty"`
	CalType       string                          `json:"cal_type,omitempty"`
	NotifyUrl     string                          `json:"notify_url,omitempty"`
	RecvDatas     []V3SacsSeparateRequestRecvData `json:"recv_datas"`
}

func (r *V3SacsSeparateRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3SacsSeparateRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_SACS_SEPARATE
}

type V3SacsSeparateRequestRecvData struct {
	RecvMerchantNo string `json:"recv_merchant_no,omitempty"`
	RecvNo         string `json:"recv_no,omitempty"`
	SeparateValue  string `json:"separate_value,omitempty"`
}
