// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3SacsQueryAmtRequest struct {
	V3Common
	MerchantNo string `json:"merchant_no,omitempty"`
	LogNo      string `json:"log_no,omitempty"`
	LogDate    string `json:"log_date,omitempty"`
}

func (r *V3SacsQueryAmtRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3SacsQueryAmtRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_SACS_QUERYAMT
}
