// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3SacsBalanceSeparateRequest struct {
	V3Common
	MerchantNo    string                                 `json:"merchant_no,omitempty"`
	OutSeparateNo string                                 `json:"out_separate_no,omitempty"` //商户分账指令流水号，每个商户号下唯一，否则会校验失败
	TotalAmt      string                                 `json:"total_amt,omitempty"`       //[单位：分]
	LklOrgNo      string                                 `json:"lkl_org_no,omitempty"`
	CalType       string                                 `json:"cal_type,omitempty"` //0- 按照指定金额，1- 按照指定比例。默认 0
	NotifyUrl     string                                 `json:"notify_url,omitempty"`
	RecvDatas     []V3SacsBalanceSeparateRequestRecvData `json:"recv_datas,omitempty"`
	LogDate       string                                 `json:"log_date"`
	LogNo         string                                 `json:"log_no"`
	SeparateType  string                                 `json:"separate_type"`
}

func (r *V3SacsBalanceSeparateRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3SacsBalanceSeparateRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_SACS_BALANCESEPARATE
}

type V3SacsBalanceSeparateRequestRecvData struct {
	RecvMerchantNo string `json:"recv_merchant_no,omitempty"`
	RecvNo         string `json:"recv_no,omitempty"`
	SeparateValue  string `json:"separate_value,omitempty"`
}
