// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

// 原skd无，自行实现分账指定分账规则
type V3SacsSeparatePointRulesRequest struct {
	V3Common
	MerNo    string `json:"mer_no"`
	RuleId   string `json:"rule_id"`
	LogNo    string `json:"log_no"`
	LogDate  string `json:"log_date"`
	OutSepNo string `json:"out_sep_no"`
}

func (r *V3SacsSeparatePointRulesRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3SacsSeparatePointRulesRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_SACS_SEPARATE_POINTRULESEPARATE
}
