// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3SacsBalanceFallbackRequest struct {
	V3Common
	MerchantNo          string                                       `json:"merchant_no,omitempty"`
	OriginSeparateNo    string                                       `json:"origin_separate_no,omitempty"`
	OutSeparateNo       string                                       `json:"out_separate_no,omitempty"`
	OriginOutSeparateNo string                                       `json:"origin_out_separate_no,omitempty"`
	FallbackReason      string                                       `json:"fallback_reason,omitempty"`
	TotalAmt            string                                       `json:"total_amt,omitempty"`
	OriginRecvDatas     []V3SacsBalanceFallbackRequestOriginRecvData `json:"origin_recv_datas,omitempty"`
}

func (r *V3SacsBalanceFallbackRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3SacsBalanceFallbackRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_SACS_BALANCEFALLBACK
}

type V3SacsBalanceFallbackRequestOriginRecvData struct {
	RecvNo string `json:"recv_no,omitempty"`
	Amt    string `json:"amt,omitempty"`
}
