// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package request

import (
	"github.com/lakala/laop-sdk-go/pkg/laopsdk/enums"
)

type V3SacsCancelRequest struct {
	V3Common
	MerchantNo          string `json:"merchant_no,omitempty"`
	OriginSeparateNo    string `json:"origin_separate_no,omitempty"`
	OriginOutSeparateNo string `json:"origin_out_separate_no,omitempty"`
	OutSeparateNo       string `json:"out_separate_no,omitempty"`
	TotalAmt            string `json:"total_amt,omitempty"`
}

func (r *V3SacsCancelRequest) ToBody() (string, error) {
	return r.BuildBody(r)
}

func (r *V3SacsCancelRequest) FunctionCode() enums.FunctionCode {
	return enums.API_V3_SACS_CANCEL
}
