// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3CcssOrderSceneOnlineWildcardBillAddress struct {
	HouseNumberOrName string `json:"houseNumberOrName,omitempty"`
	Street            string `json:"street,omitempty"`
	City              string `json:"city,omitempty"`
	Country           string `json:"country,omitempty"`
	StateOrProvince   string `json:"stateOrProvince,omitempty"`
	PostalCode        string `json:"postalCode,omitempty"`
}
