// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3CcssOrderSceneFieldInfo struct {
	OrderSceneType string `json:"order_scene_type,omitempty"`
	EncryptedField string `json:"encrypted_field,omitempty"`
	SceneInfo      string `json:"scene_info,omitempty"`
}

type V3CcssOrderSceneFieldInfoHbFqSceneInfo struct {
	HbFqNum           string `json:"hbFqNum,omitempty"`
	HbFqSellerPercent string `json:"hbFqSellerPercent,omitempty"`
}

type V3CcssOrderSceneFieldInfoOnlineWildcardSceneInfo struct {
	UserId                   string `json:"userId,omitempty"`
	UserCreateDate           string `json:"userCreateDate,omitempty"`
	RecipientStreet          string `json:"recipientStreet,omitempty"`
	RecipientCity            string `json:"recipientCity,omitempty"`
	RecipientStateOrProvince string `json:"recipientStateOrProvince,omitempty"`
	RecipientCountry         string `json:"recipientCountry,omitempty"`
}

type V3CcssOrderSceneFieldInfoUnFqInfo struct {
	IsForce           string `json:"isForce,omitempty"`
	UnFqNum           string `json:"unFqNum,omitempty"`
	UnFqSellerPercent string `json:"unFqSellerPercent,omitempty"`
}

type V3CcssOrderSceneFieldInfoKlFqSceneInfo struct {
	Unfq string `json:"UNFQ,omitempty"`
	Hbfq string `json:"HBFQ,omitempty"`
}

type V3CcssOrderSceneFieldInfoOnlineWildcardEncryptedField struct {
	BillingAddress     string `json:"billingAddress,omitempty"`
	MobilePhone        string `json:"mobilePhone,omitempty"`
	Email              string `json:"email,omitempty"`
	RecipientFirstName string `json:"recipientFirstName,omitempty"`
	RecipientLastName  string `json:"recipientLastName,omitempty"`
}

type V3CcssOrderSceneFieldInfoKlFqEncryptedField struct {
	Unfq string `json:"UNFQ,omitempty"`
}
