// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3CcssOrderGoodsFieldInfo struct {
	GoodsAmt         int64  `json:"goods_amt,omitempty"`
	GoodsNum         int    `json:"goods_num,omitempty"`
	GoodsPricingUnit string `json:"goods_pricing_unit,omitempty"`
	GoodsName        string `json:"goods_name,omitempty"`
	TePlatformType   string `json:"te_platform_type,omitempty"`
	TePlatformName   string `json:"te_platform_name,omitempty"`
	GoodsType        string `json:"goods_type,omitempty"`
}
