// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3CcssOrderSceneKlFqUnFqInfo struct {
	CardNo string `json:"cardNo,omitempty"`
	BankNm string `json:"bankNm,omitempty"`
}
