// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3CcssOrderOutSplitInfo struct {
	OutSubOrderNo string `json:"out_sub_order_no,omitempty"`
	MerchantNo    string `json:"merchant_no,omitempty"`
	TermNo        string `json:"term_no,omitempty"`
	Amount        string `json:"amount,omitempty"`
	SettleType    string `json:"settle_type,omitempty"`
}
