// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3IpsDiscountInfo struct {
	DiscountUse int    `json:"discount_use,omitempty"`
	DiscountId  string `json:"discount_id,omitempty"`
	DiscountAmt string `json:"discount_amt,omitempty"`
}
