// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3IpsdfPayerInfo struct {
	IdentityType   string `json:"identity_type,omitempty"`
	BankNo         string `json:"bank_no,omitempty"`
	BankName       string `json:"bank_name,omitempty"`
	AcctNo         string `json:"acct_no,omitempty"`
	AcctName       string `json:"acct_name,omitempty"`
	AcctType       string `json:"acct_type,omitempty"`
	BankBranchNo   string `json:"bank_branch_no,omitempty"`
	BankBranchName string `json:"bank_branch_name,omitempty"`
}
