// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3IpsTermInfo struct {
	DeviceIp string `json:"device_ip,omitempty"`
	Mac      string `json:"mac,omitempty"`
	Imei     string `json:"imei,omitempty"`
	Imsi     string `json:"imsi,omitempty"`
	Iccid    string `json:"iccid,omitempty"`
	WifiMac  string `json:"wifi_mac,omitempty"`
	Gps      string `json:"gps,omitempty"`
}
