// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3IpsRskInfo struct {
	DeviceMode              string `json:"device_mode,omitempty"`
	DeviceLanguage          string `json:"device_language,omitempty"`
	SourceIp                string `json:"source_ip,omitempty"`
	Mac                     string `json:"mac,omitempty"`
	DevId                   string `json:"dev_id,omitempty"`
	ExtensiveDeviceLocation string `json:"extensive_deviceLocation,omitempty"`
	DeviceNumber            string `json:"device_number,omitempty"`
	DeviceSimNumber         string `json:"device_sim_number,omitempty"`
	AccountIdHash           string `json:"account_id_hash,omitempty"`
	RiskScore               string `json:"risk_score,omitempty"`
	RiskReasonCode          string `json:"risk_reason_code,omitempty"`
	MchntUsrRgstrTm         string `json:"mchnt_usr_rgstr_tm,omitempty"`
	MchntUsrRgstrEmail      string `json:"mchnt_usr_rgstr_email,omitempty"`
	RcvProvince             string `json:"rcv_province,omitempty"`
	RcvCity                 string `json:"rcv_city,omitempty"`
	GoodsClass              string `json:"goods_class,omitempty"`
}
