// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3IpsCustomerInfo struct {
	CertifTp   string `json:"certif_tp,omitempty"`
	CertifId   string `json:"certif_id,omitempty"`
	CustomerNm string `json:"customer_nm,omitempty"`
	SmsCode    string `json:"sms_code,omitempty"`
	Pin        string `json:"pin,omitempty"`
	Cvn2       string `json:"cvn2,omitempty"`
	Expired    string `json:"expired,omitempty"`
	PhoneNo    string `json:"phone_no,omitempty"`
}
