// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3IpsSgnInfo struct {
	SngAcctTp  string `json:"sng_acct_tp,omitempty"`
	SgnAcctId  string `json:"sgn_acct_id,omitempty"`
	IssInsCode string `json:"iss_ins_code,omitempty"`
	SgnAcctNm  string `json:"sgn_acct_nm,omitempty"`
	IdTp       string `json:"id_tp,omitempty"`
	IdNo       string `json:"id_no,omitempty"`
	MobNo      string `json:"mob_no,omitempty"`
	Cvn2       string `json:"cvn2,omitempty"`
	VaDate     string `json:"va_date,omitempty"`
}
