// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3LabsTradePreorderNucspayBus struct {
	V3LabsTradeAccBusiFieldInfo
	NucIssrId string `json:"nuc_issr_id,omitempty"`
}
