// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3LabsTradeLocationInfo struct {
	RequestIp   string `json:"request_ip,omitempty"`
	BaseStation string `json:"base_station,omitempty"`
	Location    string `json:"location,omitempty"`
}
