// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3LabsTradeMicropayAlipayBus struct {
	V3LabsTradeAccBusiFieldInfo
	ExtendParams       V3LabsTradeMicropayAlipayBusAlipayExtendParamInfo `json:"extend_params,omitempty"`
	GoodsDetail        []V3LabsTradeMicropayAlipayBusAlipayGoodsDeTail   `json:"goods_detail,omitempty"`
	StoreId            string                                            `json:"store_id,omitempty"`
	TimeoutExpress     string                                            `json:"timeout_express,omitempty"`
	DisablePayChannels string                                            `json:"disable_pay_channels,omitempty"`
	BusinessParams     string                                            `json:"business_params,omitempty"`
	MinAge             string                                            `json:"min_age,omitempty"`
}

type V3LabsTradeMicropayAlipayBusAlipayExtendParamInfo struct {
	SysServiceProviderId string `json:"sys_service_provider_id,omitempty"`
	HbFqNum              string `json:"hb_fq_num,omitempty"`
	HbFqSellerPercent    string `json:"hb_fq_seller_percent,omitempty"`
}

type V3LabsTradeMicropayAlipayBusAlipayGoodsDeTail struct {
	GoodsId        string `json:"goods_id,omitempty"`
	AlipayGoodsId  string `json:"alipay_goods_id,omitempty"`
	GoodsName      string `json:"goods_name,omitempty"`
	Quantity       string `json:"quantity,omitempty"`
	Price          string `json:"price,omitempty"`
	GoodsCategory  string `json:"goods_category,omitempty"`
	CategoriesTree string `json:"categories_tree,omitempty"`
	Body           string `json:"body,omitempty"`
	ShowUrl        string `json:"show_url,omitempty"`
}
