// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3LabsTradeMicropayUnionPayBus struct {
	V3LabsTradeAccBusiFieldInfo
	AcqAddnDataOrderInfo string `json:"acq_addn_data_order_info,omitempty"`
	AcqAddnDataGoodsInfo string `json:"acq_addn_data_goods_info,omitempty"`
}
