// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3LabsTradeMicropayWechatBus struct {
	V3LabsTradeAccBusiFieldInfo
	SubAppid   string                                    `json:"sub_appid,omitempty"`
	Detail     V3LabsTradeMicropayWechatBusAccBusiDetail `json:"detail,omitempty"`
	GoodsTag   string                                    `json:"goods_tag,omitempty"`
	DeviceInfo string                                    `json:"device_info,omitempty"`
	LimitPay   string                                    `json:"limit_pay,omitempty"`
	SceneInfo  string                                    `json:"scene_info,omitempty"`
	LimitPayer string                                    `json:"limit_payer,omitempty"`
}

type V3LabsTradeMicropayWechatBusAccBusiDetail struct {
	CostPrice   int                                             `json:"cost_price,omitempty"`
	ReceiptId   string                                          `json:"receipt_id,omitempty"`
	GoodsDetail []V3LabsTradeMicropayWechatBusWechatGoodsDetail `json:"goods_detail,omitempty"`
}

type V3LabsTradeMicropayWechatBusWechatGoodsDetail struct {
	GoodsId      string `json:"goods_id,omitempty"`
	WxpayGoodsId string `json:"wxpay_goods_id,omitempty"`
	GoodsName    string `json:"goods_name,omitempty"`
	Quantity     int    `json:"quantity,omitempty"`
	Price        int    `json:"price,omitempty"`
}
