// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3LabsTradePreorderUnionPayBus struct {
	V3LabsTradeAccBusiFieldInfo
	UserId               string `json:"user_id,omitempty"`
	TimeoutExpress       string `json:"timeout_express,omitempty"`
	AcqAddnDataOrderInfo string `json:"acq_addn_data_order_info,omitempty"`
	AcqAddnDataGoodsInfo string `json:"acq_addn_data_goods_info,omitempty"`
	FrontUrl             string `json:"front_url,omitempty"`
	FrontFailUrl         string `json:"front_fail_url,omitempty"`
	InstalWill           string `json:"instal_will,omitempty"`
}
