// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3LabsTransShareCodeAlipayBus struct {
	V3LabsTransShareCodeBusiFieldInfo
	Source   string                               `json:"source,omitempty"`
	BizLink  string                               `json:"biz_link,omitempty"`
	SellerId string                               `json:"seller_id,omitempty"`
	ExtInfo  V3LabsTransShareCodeAlipayBusExtInfo `json:"ext_info,omitempty"`
}

type V3LabsTransShareCodeAlipayBusExtInfo struct {
	Fq_number       string `json:"fq_number,omitempty"`
	FqSellerPercent string `json:"fq_seller_percent,omitempty"`
}
