// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3RefundSplitInfo struct {
	OutSubTradeNo       string `json:"out_sub_trade_no,omitempty"`
	MerchantNo          string `json:"merchant_no,omitempty"`
	TermNo              string `json:"term_no,omitempty"`
	RefundAmount        string `json:"refund_amount,omitempty"`
	OriginOutSubTradeNo string `json:"origin_out_sub_trade_no,omitempty"`
	OriginSubTradeNo    string `json:"origin_sub_trade_no,omitempty"`
	OriginSubLogNo      string `json:"origin_sub_log_no,omitempty"`
	RefundAccMode       string `json:"refund_acc_mode,omitempty"`
}
