// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3SacsSeparateRecvDatas struct {
	RecvMerchantNo string `json:"recv_merchant_no,omitempty"`
	RecvNo         string `json:"recv_no,omitempty"`
	SeparateValue  string `json:"separate_value,omitempty"`
}
