// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package model

type V3TransIdentityInfo struct {
	IdentityNo   string `json:"identityNo,omitempty"`
	Name         string `json:"name,omitempty"`
	IdentityType string `json:"identityType,omitempty"`
}
