// Code generated by scripts/generate_requests.py; DO NOT EDIT.
package enums

var (
	API_V3_LABS_QUERY_TRADEQUERY           = FunctionCode{Code: "/api/v3/labs/query/tradequery", Name: "聚合扫码-交易查询"}
	API_V3_LABS_TRANS_PREORDER             = FunctionCode{Code: "/api/v3/labs/trans/preorder", Name: "聚合扫码-聚合主扫"}
	API_V3_LABS_TRANS_MICROPAY             = FunctionCode{Code: "/api/v3/labs/trans/micropay", Name: "聚合扫码-聚合被扫"}
	API_V3_LABS_RELATION_REFUND            = FunctionCode{Code: "/api/v3/labs/relation/refund", Name: "聚合扫码-退款交易"}
	API_V3_SACS_SEPARATE                   = FunctionCode{Code: "/api/v3/sacs/separate", Name: "分账指令V3接口-订单分账"}
	API_V3_SACS_QUERYAMT                   = FunctionCode{Code: "/api/v3/sacs/queryAmt", Name: "分账指令V3接口-可分账金额查询"}
	API_V3_SACS_QUERY                      = FunctionCode{Code: "/api/v3/sacs/query", Name: "分账指令V3接口-分账结果查询"}
	API_V3_SACS_SEPARATE_POINTRULESEPARATE = FunctionCode{Code: "/api/v3/srfs/separate/pointRuleSep", Name: "分账指令V3接口-指定规则分账"}

	API_V3_LABS_QUERY_IDMREFUNDQUERY                = FunctionCode{Code: "/api/v3/labs/query/idmrefundquery", Name: "商户订单退款查询"}
	API_V3_LABS_RELATION_IDMREFUND                  = FunctionCode{Code: "/api/v3/labs/relation/idmrefund", Name: "商户订单退款交易"}
	API_V3_LABS_RELATION_CLOSE                      = FunctionCode{Code: "/api/v3/labs/relation/close", Name: "聚合扫码-关单"}
	API_V3_LABS_RELATION_REVOKED                    = FunctionCode{Code: "/api/v3/labs/relation/revoked", Name: "扫码-撤销"}
	API_V3_CCSS_COUNTER_ORDER_SPECIAL_CREATE        = FunctionCode{Code: "/api/v3/ccss/counter/order/special_create", Name: "收银台订单创建"}
	API_V3_CCSS_COUNTER_ORDER_QUERY                 = FunctionCode{Code: "/api/v3/ccss/counter/order/query", Name: "收银台订单查询"}
	API_V3_SACS_CANCEL                              = FunctionCode{Code: "/api/v3/sacs/cancel", Name: "订单分账撤销"}
	API_V3_SACS_FALLBACK                            = FunctionCode{Code: "/api/v3/sacs/fallback", Name: "订单分账回退"}
	API_V3_SACS_BALANCESEPARATE                     = FunctionCode{Code: "/api/v3/sacs/balanceSeparate", Name: "余额分账"}
	API_V3_SACS_BALANCECANCEL                       = FunctionCode{Code: "/api/v3/sacs/balanceCancel", Name: "余额分账撤销"}
	API_V3_SACS_BALANCEFALLBACK                     = FunctionCode{Code: "/api/v3/sacs/balanceFallback", Name: "余额分账回退"}
	API_V3_SACS_BALANCESEPARATEQUERY                = FunctionCode{Code: "/api/v3/sacs/balanceSeparateQuery", Name: "余额分账结果查询"}
	API_V3_LABS_TRANS_SHARE_CODE                    = FunctionCode{Code: "/api/v3/labs/trans/share_code", Name: "支付类接口-申请分享码(支付宝吱口令)"}
	API_V3_LABS_TRANS_PREORDER_ENCRY                = FunctionCode{Code: "/api/v3/labs/trans/preorder_encry", Name: "支付类接口-主扫交易接口（全报文加密）"}
	API_V3_LABS_TRANS_MICROPAY_ENCRY                = FunctionCode{Code: "/api/v3/labs/trans/micropay_encry", Name: "支付类接口-被扫接口（全报文加密）"}
	API_V3_CCSS_COUNTER_ORDER_SPECIAL_CREATE_ENCRY  = FunctionCode{Code: "/api/v3/ccss/counter/order/special_create_encry", Name: "收银台服务系统-收银台订单创建 （全报文加密）"}
	API_V3_LABS_QUERY_GETFACEAUTHINFO               = FunctionCode{Code: "/api/v3/labs/query/getfaceauthinfo", Name: "支付类接口-微信刷脸授权信息获取"}
	API_V3_LAMS_MERCHANT_QUERY_TRANS                = FunctionCode{Code: "/api/v3/lams/merchant/query_trans", Name: "商户服务接口V3.0-商户计费查询"}
	API_V3_LAMS_TRADE_TRADE_REFUND                  = FunctionCode{Code: "/api/v3/lams/trade/trade_refund", Name: "商户服务接口V3.0-统一退货"}
	API_V3_LAMS_TRADE_TRADE_REFUND_QUERY            = FunctionCode{Code: "/api/v3/lams/trade/trade_refund_query", Name: "商户服务接口V3.0-退货查询"}
	API_V3_IPSQP_TRANS_QUICKSIGNAPPLY               = FunctionCode{Code: "/api/v3/ipsqp/trans/quickSignApply", Name: "快捷签约申请(发送短信)"}
	API_V3_IPSQP_TRANS_QUICKSIGNCONFIRM             = FunctionCode{Code: "/api/v3/ipsqp/trans/quickSignConfirm", Name: "快捷签约确认"}
	API_V3_IPSQP_TRANS_QUICKSIGNCANCEL              = FunctionCode{Code: "/api/v3/ipsqp/trans/quickSignCancel", Name: "快捷解约"}
	API_V3_IPSQP_TRANS_APPLYQUICKPAY                = FunctionCode{Code: "/api/v3/ipsqp/trans/applyQuickPay", Name: "快捷支付申请（已有协议号）"}
	API_V3_IPSQP_TRANS_CONFIRMQUICKPAY              = FunctionCode{Code: "/api/v3/ipsqp/trans/confirmQuickPay", Name: "快捷支付确认接口（已有协议号）"}
	API_V3_IPSQP_TRANS_APPLYSIGNANDPAY              = FunctionCode{Code: "/api/v3/ipsqp/trans/applySignAndPay", Name: "快捷签约并支付申请（没有协议号）"}
	API_V3_IPSQP_TRANS_CONFIRMSIGNANDPAY            = FunctionCode{Code: "/api/v3/ipsqp/trans/confirmSignAndPay", Name: "快捷支付确认接口（没有协议号）"}
	API_V3_IPSQP_QUERY_TRADEQUERY                   = FunctionCode{Code: "/api/v3/ipsqp/query/tradeQuery", Name: "代收查询"}
	API_V3_IPSQP_TRANS_GATEWAYSIGN                  = FunctionCode{Code: "/api/v3/ipsqp/trans/gatewaySign", Name: "网关签约（一键绑卡）"}
	API_V3_IPSQP_TRANS_DIRECTLYQUICKPAY             = FunctionCode{Code: "/api/v3/ipsqp/trans/directlyQuickPay", Name: "快捷直接支付"}
	API_V3_IPSQP_QUERY_QUERYSIGNBYPAN               = FunctionCode{Code: "/api/v3/ipsqp/query/querySignByPan", Name: "根据卡号查询协议号"}
	API_V3_IPSDK_TRANS_COLLECTIONSIGNAPPLY          = FunctionCode{Code: "/api/v3/ipsdk/trans/collectionSignApply", Name: "代收签约申请(发送短信)"}
	API_V3_IPSDK_TRANS_COLLECTIONSIGNCONFIRM        = FunctionCode{Code: "/api/v3/ipsdk/trans/collectionSignConfirm", Name: "代收签约确认"}
	API_V3_IPSDK_TRANS_COLLECTIONSIGNCANCEL         = FunctionCode{Code: "/api/v3/ipsdk/trans/collectionSignCancel", Name: "代收解约"}
	API_V3_IPSDK_TRANS_BATCHCOLLECTION              = FunctionCode{Code: "/api/v3/ipsdk/trans/batchCollection", Name: "批量代收"}
	API_V3_IPSDK_TRANS_BATCHQUERY                   = FunctionCode{Code: "/api/v3/ipsdk/trans/batchQuery", Name: "批量代收查询"}
	API_V3_IPSDK_TRANS_REALTIMECOLLECTION           = FunctionCode{Code: "/api/v3/ipsdk/trans/realTimeCollection", Name: "实时代收"}
	API_V3_IPSDK_RELATION_REFUND                    = FunctionCode{Code: "/api/v3/ipsdk/relation/refund", Name: "代收退款"}
	API_V3_IPSDF_PAID_PAY                           = FunctionCode{Code: "/api/v3/ipsdf/paid/pay", Name: "实时代付接口"}
	API_V3_IPSDF_PAID_QUERY                         = FunctionCode{Code: "/api/v3/ipsdf/paid/query", Name: "实时代付查询接口"}
	API_V3_IPSDF_PAID_BATCHPAY                      = FunctionCode{Code: "/api/v3/ipsdf/paid/batchPay", Name: "批量代付接口"}
	API_V3_IPSDF_PAID_BATCHQUERY                    = FunctionCode{Code: "/api/v3/ipsdf/paid/batchQuery", Name: "批量代付查询接口"}
	API_V3_CCSS_COUNTER_ORDER_CLOSE                 = FunctionCode{Code: "/api/v3/ccss/counter/order/close", Name: "收银台关单"}
	API_V3_RFD_REFUND_FRONT_REFUND                  = FunctionCode{Code: "/api/v3/rfd/refund_front/refund", Name: "退货前置-退货(同步)"}
	API_V3_RFD_REFUND_FRONT_REFUND_QUERY            = FunctionCode{Code: "/api/v3/rfd/refund_front/refund_query", Name: "退货前置-退货查询"}
	API_V3_RFD_REFUND_FRONT_REFUND_FEE              = FunctionCode{Code: "/api/v3/rfd/refund_front/refund_fee", Name: "退货前置-退货手续费试算"}
	API_V3_RFD_REFUND_FRONT_MERGE_REFUND            = FunctionCode{Code: "/api/v3/rfd/refund_front/merge_refund", Name: "退货前置-合单退货"}
	API_V2_MMS_OPENAPI_LEDGER_APPLYLEDGERMER        = FunctionCode{Code: "/api/v2/mms/openApi/ledger/applyLedgerMer", Name: "商户分账业务开通申请"}
	API_V2_MMS_OPENAPI_LEDGER_MODIFYLEDGERMER       = FunctionCode{Code: "/api/v2/mms/openApi/ledger/modifyLedgerMer", Name: "商户分账信息变更申请"}
	API_V2_MMS_OPENAPI_LEDGER_QUERYLEDGERMER        = FunctionCode{Code: "/api/v2/mms/openApi/ledger/queryLedgerMer", Name: "分账商户信息查询"}
	API_V2_MMS_OPENAPI_LEDGER_APPLYLEDGERRECEIVER   = FunctionCode{Code: "/api/v2/mms/openApi/ledger/applyLedgerReceiver", Name: "分账接收方开通申请"}
	API_V2_MMS_OPENAPI_LEDGER_MODIFYLEDGERRECEIVER  = FunctionCode{Code: "/api/v2/mms/openApi/ledger/modifyLedgerReceiver", Name: "分账接收方信息变更申请"}
	API_V2_MMS_OPENAPI_LEDGER_DETAILlLEDGERRECEIVER = FunctionCode{Code: "/api/v2/mms/openApi/ledger/queryReceiverDetail", Name: "分账接收方详情查询"}
	API_V2_MMS_OPENAPI_LEDGER_APPLYBIND             = FunctionCode{Code: "/api/v2/mms/openApi/ledger/applyBind", Name: "分账关系绑定申请"}
	API_V2_MMS_OPENAPI_LEDGER_APPLYUNBIND           = FunctionCode{Code: "/api/v2/mms/openApi/ledger/applyUnBind", Name: "分账关系解绑申请"}
	API_V2_MMS_OPENAPI_ACTIVESETTLE_APPLY           = FunctionCode{Code: "/api/v2/mms/openApi/activeSettle/apply", Name: "商户开通主动结算业务"}
	API_V2_LAEP_INDUSTRY_EWALLETWITHDRAW            = FunctionCode{Code: "/api/v2/laep/industry/ewalletWithdraw", Name: "账管家V2.0-账管家提现"}
	API_V2_LAEP_INDUSTRY_EWALLETWITHDRAWQUERY       = FunctionCode{Code: "/api/v2/laep/industry/ewalletWithdrawQuery", Name: "账管家V2.0-账管家提现结果查询"}
	API_V2_LAEP_INDUSTRY_EWALLET_SETTLEPROFILE      = FunctionCode{Code: "/api/v2/laep/industry/ewallet/settleProfile", Name: "账管家V2.0-账管家提款模式设置"}
	API_V2_LAEP_INDUSTRY_EWALLET_SETTLEQUERY        = FunctionCode{Code: "/api/v2/laep/industry/ewallet/settleQuery", Name: "账管家V2.0-账管家提款模式查询"}
	API_V2_LAEP_INDUSTRY_EWALLET_EWALLETFEE         = FunctionCode{Code: "/api/v2/laep/industry/ewallet/ewalletfee", Name: "账管家V2.0-账管家提款手续费设置"}
	API_V2_LAEP_INDUSTRY_EWALLET_QUERYFEE           = FunctionCode{Code: "/api/v2/laep/industry/ewallet/queryfee", Name: "账管家V2.0-账管家提款手续费查询"}
	API_V2_LAEP_INDUSTRY_EWALLETWITHDRAWD1          = FunctionCode{Code: "/api/v2/laep/industry/ewalletWithdrawD1", Name: "账管家V2.0-账管家提现D1"}
	API_V2_LAEP_INDUSTRY_TRANSFER_DIRECT            = FunctionCode{Code: "/api/v2/laep/industry/transfer/direct", Name: "账管家V2.0-可用余额定向转账"}
	API_V2_LAEP_INDUSTRY_TRANSFER_QUERY             = FunctionCode{Code: "/api/v2/laep/industry/transfer/query", Name: "账管家V2.0-转账订单查询"}
	API_V2_LAEP_INDUSTRY_EWALLETBALANCEQUERY        = FunctionCode{Code: "/api/v2/laep/industry/ewalletBalanceQuery", Name: "账管家V2.0-账管家余额查询"}
	API_V2_LAEP_EWALLETACCOUNT_QUERYACCTINFO        = FunctionCode{Code: "/api/v2/laep/ewalletAccount/queryAcctInfo", Name: "账管家V2.0-收单账户信息查询"}
	API_V2_MRSSQUERY_QUERYACCTINFO                  = FunctionCode{Code: "/api/v2/mrssQuery/queryAcctInfo", Name: "收单清结算接口V2-账户信息查询"}
	API_V2_LAEP_INDUSTRY_BANKCARD_BIND              = FunctionCode{Code: "/api/v2/laep/industry/bankcard/bind", Name: "账管家V2.0-绑定银行卡"}
	API_V2_LAEP_INDUSTRY_BANKCARD_LIST              = FunctionCode{Code: "/api/v2/laep/industry/bankcard/list", Name: "账管家V2.0-查询银行卡列表"}
	API_V2_LAEP_INDUSTRY_BANKCARD_UNBIND            = FunctionCode{Code: "/api/v2/laep/industry/bankcard/unbind", Name: "账管家V2.0-解绑银行卡"}
	API_V2_LAEP_EWALLETACCOUNT_BILLSQRY             = FunctionCode{Code: "/api/v2/laep/ewalletAccount/billsQry", Name: "账管家V2.0-账单分页查询"}
	API_V2_LAEP_CREATEELERECEIPT                    = FunctionCode{Code: "/api/v2/laep/createEleReceipt", Name: "账管家V2.0-生成电子回单"}
	API_V2_MCQS_MERCHANT_QUERYMERCHANTDETAIL        = FunctionCode{Code: "/api/v2/mcqs/merchant/queryMerchantDetail", Name: "商户信息查询"}
	API_V2_MCQS_LIMIT_QUERYLIMIT                    = FunctionCode{Code: "/api/v2/mcqs/limit/queryLimit", Name: "商户限额查询"}
	API_V2_MCQS_MERCHANT_QUERYMERACCOUNT            = FunctionCode{Code: "/api/v2/mcqs/merchant/queryMerAccount", Name: "商户结算账户查询"}
	API_V2_MCQS_MERCHANT_QUERYTERMACCOUNT           = FunctionCode{Code: "/api/v2/mcqs/merchant/queryTermAccount", Name: "终端结算账户查询"}
	API_V2_MCQS_BUSI_QUERYTERMTRANTYPE              = FunctionCode{Code: "/api/v2/mcqs/busi/queryTermTranType", Name: "终端交易权限查询"}
	API_V2_MCQS_MERCHANT_QUERYSHOPLISTBYNUM         = FunctionCode{Code: "/api/v2/mcqs/merchant/queryShopListByNum", Name: "商户网点列表查询"}
	API_V2_MCQS_BUSI_QUERYBUSILISTBYNUM             = FunctionCode{Code: "/api/v2/mcqs/busi/queryBusiListByNum", Name: "商户终端列表查询"}
	API_V2_MCQS_BUSI_QUERYTERMFEE                   = FunctionCode{Code: "/api/v2/mcqs/busi/queryTermFee", Name: "终端费率查询"}
	API_V2_MMS_OPENAPI_UPLOADFILE                   = FunctionCode{Code: "/api/v2/mms/openApi/uploadFile", Name: "附件上传"}
)

var functionCodeIndex = map[string]FunctionCode{
	"API_V3_LABS_QUERY_TRADEQUERY":                   API_V3_LABS_QUERY_TRADEQUERY,
	"API_V3_LABS_TRANS_PREORDER":                     API_V3_LABS_TRANS_PREORDER,
	"API_V3_LABS_TRANS_MICROPAY":                     API_V3_LABS_TRANS_MICROPAY,
	"API_V3_LABS_RELATION_REFUND":                    API_V3_LABS_RELATION_REFUND,
	"API_V3_SACS_SEPARATE":                           API_V3_SACS_SEPARATE,
	"API_V3_SACS_QUERYAMT":                           API_V3_SACS_QUERYAMT,
	"API_V3_SACS_QUERY":                              API_V3_SACS_QUERY,
	"API_V3_LABS_QUERY_IDMREFUNDQUERY":               API_V3_LABS_QUERY_IDMREFUNDQUERY,
	"API_V3_LABS_RELATION_IDMREFUND":                 API_V3_LABS_RELATION_IDMREFUND,
	"API_V3_LABS_RELATION_CLOSE":                     API_V3_LABS_RELATION_CLOSE,
	"API_V3_LABS_RELATION_REVOKED":                   API_V3_LABS_RELATION_REVOKED,
	"API_V3_CCSS_COUNTER_ORDER_SPECIAL_CREATE":       API_V3_CCSS_COUNTER_ORDER_SPECIAL_CREATE,
	"API_V3_CCSS_COUNTER_ORDER_QUERY":                API_V3_CCSS_COUNTER_ORDER_QUERY,
	"API_V3_SACS_CANCEL":                             API_V3_SACS_CANCEL,
	"API_V3_SACS_FALLBACK":                           API_V3_SACS_FALLBACK,
	"API_V3_SACS_BALANCESEPARATE":                    API_V3_SACS_BALANCESEPARATE,
	"API_V3_SACS_BALANCECANCEL":                      API_V3_SACS_BALANCECANCEL,
	"API_V3_SACS_BALANCEFALLBACK":                    API_V3_SACS_BALANCEFALLBACK,
	"API_V3_SACS_BALANCESEPARATEQUERY":               API_V3_SACS_BALANCESEPARATEQUERY,
	"API_V3_LABS_TRANS_SHARE_CODE":                   API_V3_LABS_TRANS_SHARE_CODE,
	"API_V3_LABS_TRANS_PREORDER_ENCRY":               API_V3_LABS_TRANS_PREORDER_ENCRY,
	"API_V3_LABS_TRANS_MICROPAY_ENCRY":               API_V3_LABS_TRANS_MICROPAY_ENCRY,
	"API_V3_CCSS_COUNTER_ORDER_SPECIAL_CREATE_ENCRY": API_V3_CCSS_COUNTER_ORDER_SPECIAL_CREATE_ENCRY,
	"API_V3_LABS_QUERY_GETFACEAUTHINFO":              API_V3_LABS_QUERY_GETFACEAUTHINFO,
	"API_V3_LAMS_MERCHANT_QUERY_TRANS":               API_V3_LAMS_MERCHANT_QUERY_TRANS,
	"API_V3_LAMS_TRADE_TRADE_REFUND":                 API_V3_LAMS_TRADE_TRADE_REFUND,
	"API_V3_LAMS_TRADE_TRADE_REFUND_QUERY":           API_V3_LAMS_TRADE_TRADE_REFUND_QUERY,
	"API_V3_IPSQP_TRANS_QUICKSIGNAPPLY":              API_V3_IPSQP_TRANS_QUICKSIGNAPPLY,
	"API_V3_IPSQP_TRANS_QUICKSIGNCONFIRM":            API_V3_IPSQP_TRANS_QUICKSIGNCONFIRM,
	"API_V3_IPSQP_TRANS_QUICKSIGNCANCEL":             API_V3_IPSQP_TRANS_QUICKSIGNCANCEL,
	"API_V3_IPSQP_TRANS_APPLYQUICKPAY":               API_V3_IPSQP_TRANS_APPLYQUICKPAY,
	"API_V3_IPSQP_TRANS_CONFIRMQUICKPAY":             API_V3_IPSQP_TRANS_CONFIRMQUICKPAY,
	"API_V3_IPSQP_TRANS_APPLYSIGNANDPAY":             API_V3_IPSQP_TRANS_APPLYSIGNANDPAY,
	"API_V3_IPSQP_TRANS_CONFIRMSIGNANDPAY":           API_V3_IPSQP_TRANS_CONFIRMSIGNANDPAY,
	"API_V3_IPSQP_QUERY_TRADEQUERY":                  API_V3_IPSQP_QUERY_TRADEQUERY,
	"API_V3_IPSQP_TRANS_GATEWAYSIGN":                 API_V3_IPSQP_TRANS_GATEWAYSIGN,
	"API_V3_IPSQP_TRANS_DIRECTLYQUICKPAY":            API_V3_IPSQP_TRANS_DIRECTLYQUICKPAY,
	"API_V3_IPSQP_QUERY_QUERYSIGNBYPAN":              API_V3_IPSQP_QUERY_QUERYSIGNBYPAN,
	"API_V3_IPSDK_TRANS_COLLECTIONSIGNAPPLY":         API_V3_IPSDK_TRANS_COLLECTIONSIGNAPPLY,
	"API_V3_IPSDK_TRANS_COLLECTIONSIGNCONFIRM":       API_V3_IPSDK_TRANS_COLLECTIONSIGNCONFIRM,
	"API_V3_IPSDK_TRANS_COLLECTIONSIGNCANCEL":        API_V3_IPSDK_TRANS_COLLECTIONSIGNCANCEL,
	"API_V3_IPSDK_TRANS_BATCHCOLLECTION":             API_V3_IPSDK_TRANS_BATCHCOLLECTION,
	"API_V3_IPSDK_TRANS_BATCHQUERY":                  API_V3_IPSDK_TRANS_BATCHQUERY,
	"API_V3_IPSDK_TRANS_REALTIMECOLLECTION":          API_V3_IPSDK_TRANS_REALTIMECOLLECTION,
	"API_V3_IPSDK_RELATION_REFUND":                   API_V3_IPSDK_RELATION_REFUND,
	"API_V3_IPSDF_PAID_PAY":                          API_V3_IPSDF_PAID_PAY,
	"API_V3_IPSDF_PAID_QUERY":                        API_V3_IPSDF_PAID_QUERY,
	"API_V3_IPSDF_PAID_BATCHPAY":                     API_V3_IPSDF_PAID_BATCHPAY,
	"API_V3_IPSDF_PAID_BATCHQUERY":                   API_V3_IPSDF_PAID_BATCHQUERY,
	"API_V3_CCSS_COUNTER_ORDER_CLOSE":                API_V3_CCSS_COUNTER_ORDER_CLOSE,
	"API_V3_RFD_REFUND_FRONT_REFUND":                 API_V3_RFD_REFUND_FRONT_REFUND,
	"API_V3_RFD_REFUND_FRONT_REFUND_QUERY":           API_V3_RFD_REFUND_FRONT_REFUND_QUERY,
	"API_V3_RFD_REFUND_FRONT_REFUND_FEE":             API_V3_RFD_REFUND_FRONT_REFUND_FEE,
	"API_V3_RFD_REFUND_FRONT_MERGE_REFUND":           API_V3_RFD_REFUND_FRONT_MERGE_REFUND,
	"API_V2_MMS_OPENAPI_LEDGER_APPLYLEDGERMER":       API_V2_MMS_OPENAPI_LEDGER_APPLYLEDGERMER,
	"API_V2_MMS_OPENAPI_LEDGER_MODIFYLEDGERMER":      API_V2_MMS_OPENAPI_LEDGER_MODIFYLEDGERMER,
	"API_V2_MMS_OPENAPI_LEDGER_QUERYLEDGERMER":       API_V2_MMS_OPENAPI_LEDGER_QUERYLEDGERMER,
	"API_V2_MMS_OPENAPI_LEDGER_APPLYLEDGERRECEIVER":  API_V2_MMS_OPENAPI_LEDGER_APPLYLEDGERRECEIVER,
	"API_V2_MMS_OPENAPI_LEDGER_MODIFYLEDGERRECEIVER": API_V2_MMS_OPENAPI_LEDGER_MODIFYLEDGERRECEIVER,
	"API_V2_MMS_OPENAPI_LEDGER_APPLYBIND":            API_V2_MMS_OPENAPI_LEDGER_APPLYBIND,
	"API_V2_MMS_OPENAPI_LEDGER_APPLYUNBIND":          API_V2_MMS_OPENAPI_LEDGER_APPLYUNBIND,
	"API_V2_MMS_OPENAPI_ACTIVESETTLE_APPLY":          API_V2_MMS_OPENAPI_ACTIVESETTLE_APPLY,
	"API_V2_LAEP_INDUSTRY_EWALLETWITHDRAW":           API_V2_LAEP_INDUSTRY_EWALLETWITHDRAW,
	"API_V2_LAEP_INDUSTRY_EWALLETWITHDRAWQUERY":      API_V2_LAEP_INDUSTRY_EWALLETWITHDRAWQUERY,
	"API_V2_LAEP_INDUSTRY_EWALLET_SETTLEPROFILE":     API_V2_LAEP_INDUSTRY_EWALLET_SETTLEPROFILE,
	"API_V2_LAEP_INDUSTRY_EWALLET_SETTLEQUERY":       API_V2_LAEP_INDUSTRY_EWALLET_SETTLEQUERY,
	"API_V2_LAEP_INDUSTRY_EWALLET_EWALLETFEE":        API_V2_LAEP_INDUSTRY_EWALLET_EWALLETFEE,
	"API_V2_LAEP_INDUSTRY_EWALLET_QUERYFEE":          API_V2_LAEP_INDUSTRY_EWALLET_QUERYFEE,
	"API_V2_LAEP_INDUSTRY_EWALLETWITHDRAWD1":         API_V2_LAEP_INDUSTRY_EWALLETWITHDRAWD1,
	"API_V2_LAEP_INDUSTRY_TRANSFER_DIRECT":           API_V2_LAEP_INDUSTRY_TRANSFER_DIRECT,
	"API_V2_LAEP_INDUSTRY_TRANSFER_QUERY":            API_V2_LAEP_INDUSTRY_TRANSFER_QUERY,
	"API_V2_LAEP_INDUSTRY_EWALLETBALANCEQUERY":       API_V2_LAEP_INDUSTRY_EWALLETBALANCEQUERY,
	"API_V2_LAEP_EWALLETACCOUNT_QUERYACCTINFO":       API_V2_LAEP_EWALLETACCOUNT_QUERYACCTINFO,
	"API_V2_MRSSQUERY_QUERYACCTINFO":                 API_V2_MRSSQUERY_QUERYACCTINFO,
	"API_V2_LAEP_INDUSTRY_BANKCARD_BIND":             API_V2_LAEP_INDUSTRY_BANKCARD_BIND,
	"API_V2_LAEP_INDUSTRY_BANKCARD_LIST":             API_V2_LAEP_INDUSTRY_BANKCARD_LIST,
	"API_V2_LAEP_INDUSTRY_BANKCARD_UNBIND":           API_V2_LAEP_INDUSTRY_BANKCARD_UNBIND,
	"API_V2_LAEP_EWALLETACCOUNT_BILLSQRY":            API_V2_LAEP_EWALLETACCOUNT_BILLSQRY,
	"API_V2_LAEP_CREATEELERECEIPT":                   API_V2_LAEP_CREATEELERECEIPT,
	"API_V2_MCQS_MERCHANT_QUERYMERCHANTDETAIL":       API_V2_MCQS_MERCHANT_QUERYMERCHANTDETAIL,
	"API_V2_MCQS_LIMIT_QUERYLIMIT":                   API_V2_MCQS_LIMIT_QUERYLIMIT,
	"API_V2_MCQS_MERCHANT_QUERYMERACCOUNT":           API_V2_MCQS_MERCHANT_QUERYMERACCOUNT,
	"API_V2_MCQS_MERCHANT_QUERYTERMACCOUNT":          API_V2_MCQS_MERCHANT_QUERYTERMACCOUNT,
	"API_V2_MCQS_BUSI_QUERYTERMTRANTYPE":             API_V2_MCQS_BUSI_QUERYTERMTRANTYPE,
	"API_V2_MCQS_MERCHANT_QUERYSHOPLISTBYNUM":        API_V2_MCQS_MERCHANT_QUERYSHOPLISTBYNUM,
	"API_V2_MCQS_BUSI_QUERYBUSILISTBYNUM":            API_V2_MCQS_BUSI_QUERYBUSILISTBYNUM,
	"API_V2_MCQS_BUSI_QUERYTERMFEE":                  API_V2_MCQS_BUSI_QUERYTERMFEE,
	"API_V2_MMS_OPENAPI_UPLOADFILE":                  API_V2_MMS_OPENAPI_UPLOADFILE,
}

func LookupFunctionCode(name string) (FunctionCode, bool) {
	fc, ok := functionCodeIndex[name]
	return fc, ok
}
